### ISSUE TITLE
Please parse and display @params and @returns of methods separate from description text

### ISSUE THREAD

**Issue by brettnolan** [BurntSushi/pdoc#73] opened 2015-10-27 19:17 UTC
It would be really nice if the pdoc would parse and display thinks like the @params and @returns separately (and appropriately) from the rest of the description content.

So for instance, if my descriptor looked like:
```
@staticmethod
def version_str(version):
    """
    Retrieves the current version string of the software loaded on the DUT.
    @param version - A dictionary containing version information
    @return: Return a string form of the version.
    """
```
It would show separate Parameters and Returns sections in the output like:
### def version_str(version)
Retrieves the current version string of the software loaded on the DUT.

###### Parameters
&nbsp;&nbsp;&nbsp;&nbsp;**version**&nbsp;&nbsp;&nbsp;&nbsp;A dictionary containing version information

###### Returns
&nbsp;&nbsp;&nbsp;&nbsp;Return a string form of the version.

**Comment by BurntSushi** [comment] 2015-10-27 19:32
Dupe of #59.

**Closed by BurntSushi** 2015-10-27 19:32 UTC
